[toolchain]
anchor_version = "0.28.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
soul_harvest_vault = "CM7bjZs41G4ryhjUMptVRLLd1ojwxHrrE5sGfEGqV5h"

[programs.devnet]
soul_harvest_vault = "CM7bjZs41G4ryhjUMptVRLLd1ojwxHrrE5sGfEGqV5h"

[programs.mainnet]
soul_harvest_vault = "CM7bjZs41G4ryhjUMptVRLLd1ojwxHrrE5sGfEGqV5h"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
initialize-mainnet = "ts-node scripts/initialize-mainnet.ts"
